import { EMOTIONS } from "../../../types";

export const BehaviorToBody: { [key: string]: EMOTIONS } = {
  NEUTRAL: EMOTIONS.NEUTRAL,
  DISGUST: EMOTIONS.ANGRY,
  CONTEMPT: EMOTIONS.ANGRY,
  BELLIGERENCE: EMOTIONS.ANGRY,
  DOMINEERING: EMOTIONS.ANGRY,
  CRITICISM: EMOTIONS.ANGRY,
  ANGER: EMOTIONS.ANGRY,
  TENSION: EMOTIONS.ANGRY,
  TENSE_HUMOR: EMOTIONS.ANGRY,
  DEFENSIVENESS: EMOTIONS.ANGRY,
  WHINING: EMOTIONS.SAD,
  SADNESS: EMOTIONS.SAD,
  STONEWALLING: EMOTIONS.ANGRY,
  INTEREST: EMOTIONS.HAPPY,
  VALIDATION: EMOTIONS.HAPPY,
  AFFECTION: EMOTIONS.HAPPY,
  HUMOR: EMOTIONS.HAPPY,
  SURPRISE: EMOTIONS.NEUTRAL,
  JOY: EMOTIONS.HAPPY,
};