export const RPMBehaviorToFacial: { [key: string]: string } = {
  NEUTRAL: 'Neutral',
  DISGUST: 'Disgust',
  CONTEMPT: 'Disgust',
  BELLIGERENCE: 'Anger',
  DOMINEERING: 'Anger',
  CRITICISM: 'Anger',
  ANGER: 'Anger',
  TENSION: 'Fear',
  TENSE_HUMOR: 'Fear',
  DEFENSIVENESS: 'Fear',
  WHINING: 'Sadness',
  SADNESS: 'Sadness',
  STONEWALLING: 'Disgust',
  INTEREST: 'Joy',
  VALIDATION: 'Surprise',
  AFFECTION: 'Joy',
  HUMOR: 'Joy',
  SURPRISE: 'Surprise',
  JOY: 'Joy',
};
