import { EMOTIONS } from '../data/types';

// This maps the full list of emotions to the ones currently supported for
// Innequin's body expressions

export const BehaviorToBody: { [key: string]: EMOTIONS } = {
  NEUTRAL: EMOTIONS.NEUTRAL,
  DISGUST: EMOTIONS.ANGRY,
  CONTEMPT: EMOTIONS.ANGRY,
  BELLIGERENCE: EMOTIONS.ANGRY,
  DOMINEERING: EMOTIONS.ANGRY,
  CRITICISM: EMOTIONS.ANGRY,
  ANGER: EMOTIONS.ANGRY,
  TENSION: EMOTIONS.FEAR,
  TENSE_HUMOR: EMOTIONS.ANGRY,
  DEFENSIVENESS: EMOTIONS.FEAR,
  WHINING: EMOTIONS.SAD,
  SADNESS: EMOTIONS.SAD,
  STONEWALLING: EMOTIONS.NEUTRAL,
  INTEREST: EMOTIONS.HAPPY,
  VALIDATION: EMOTIONS.HAPPY,
  AFFECTION: EMOTIONS.HAPPY,
  HUMOR: EMOTIONS.HAPPY,
  SURPRISE: EMOTIONS.HAPPY,
  JOY: EMOTIONS.HAPPY,
};
